export const mainWeatherConditions = {
	dark: {
		1000: "/images/weather/dark-mode/clear-or-hot.png",
		1003: "/images/weather/dark-mode/patchy-cloud.png",
		1006: "/images/weather/dark-mode/patchy-cloud.png",
		1009: "/images/weather/dark-mode/overcast.png",
		1030: "/images/weather/dark-mode/fog.png",
		1063: "/images/weather/dark-mode/week-rain.png",
		1066: "/images/weather/dark-mode/week-snow.png",
		1069: "/images/weather/dark-mode/shower-or-drizzle.png",
		1072: "/images/weather/dark-mode/shower-or-drizzle.png",
		1087: "/images/weather/dark-mode/thunder-with-some-rain.png",
		1114: "/images/weather/dark-mode/snow.png",
		1117: "/images/weather/dark-mode/snow.png",
		1135: "/images/weather/dark-mode/fog.png",
		1147: "/images/weather/dark-mode/fog.png",
		1150: "/images/weather/dark-mode/wind.png",
		1153: "/images/weather/dark-mode/wind.png",
		1168: "/images/weather/dark-mode/shower-or-drizzle.png",
		1171: "/images/weather/dark-mode/shower-or-drizzle.png",
		1180: "/images/weather/dark-mode/week-rain.png",
		1183: "/images/weather/dark-mode/week-rain.png",
		1186: "/images/weather/dark-mode/strong-or-normal-rain.png",
		1189: "/images/weather/dark-mode/strong-or-normal-rain.png",
		1192: "/images/weather/dark-mode/strong-or-normal-rain.png",
		1195: "/images/weather/dark-mode/strong-or-normal-rain.png",
		1198: "/images/weather/dark-mode/strong-or-normal-rain.png",
		1201: "/images/weather/dark-mode/shower-or-drizzle.png",
		1204: "/images/weather/dark-mode/patchy-cloud.png",
		1210: "/images/weather/dark-mode/shower-or-drizzle.png",
		1213: "/images/weather/dark-mode/snow.png",
		1216: "/images/weather/dark-mode/snow.png",
		1219: "/images/weather/dark-mode/snow.png",
		1222: "/images/weather/dark-mode/snow.png",
		1225: "/images/weather/dark-mode/snow.png",
		1237: "/images/weather/dark-mode/snow.png",
		1240: "/images/weather/dark-mode/shower-or-drizzle.png",
		1243: "/images/weather/dark-mode/strong-or-normal-rain.png",
		1246: "/images/weather/dark-mode/shower-or-drizzle.png",
		1249: "/images/weather/dark-mode/strong-or-normal-rain.png",
		1252: "/images/weather/dark-mode/strong-or-normal-rain.png",
		1255: "/images/weather/dark-mode/snow.png",
		1258: "/images/weather/dark-mode/snow.png",
		1261: "/images/weather/dark-mode/snow.png",
		1264: "/images/weather/dark-mode/snow.png",
		1273: "/images/weather/dark-mode/thunder-with-some-rain.png",
		1276: "/images/weather/dark-mode/thunder-with-some-rain.png",
		1279: "/images/weather/dark-mode/thunder-with-some-rain.png",
		1282: "/images/weather/dark-mode/thunder-with-some-rain.png"
	},
	light: {
		1000: "/images/weather/white-mode/clear-or-hot.png",
		1003: "/images/weather/white-mode/patchy-cloud.png",
		1006: "/images/weather/white-mode/patchy-cloud.png",
		1009: "/images/weather/white-mode/overcast.png",
		1030: "/images/weather/white-mode/fog.png",
		1063: "/images/weather/white-mode/week-rain.png",
		1066: "/images/weather/white-mode/week-snow.png",
		1069: "/images/weather/white-mode/shower-or-drizzle.png",
		1072: "/images/weather/white-mode/shower-or-drizzle.png",
		1087: "/images/weather/white-mode/thunder-with-some-rain.png",
		1114: "/images/weather/white-mode/snow.png",
		1117: "/images/weather/white-mode/snow.png",
		1135: "/images/weather/white-mode/fog.png",
		1147: "/images/weather/white-mode/fog.png",
		1150: "/images/weather/white-mode/wind.png",
		1153: "/images/weather/white-mode/wind.png",
		1168: "/images/weather/white-mode/shower-or-drizzle.png",
		1171: "/images/weather/white-mode/shower-or-drizzle.png",
		1180: "/images/weather/white-mode/week-rain.png",
		1183: "/images/weather/white-mode/week-rain.png",
		1186: "/images/weather/white-mode/strong-or-normal-rain.png",
		1189: "/images/weather/white-mode/strong-or-normal-rain.png",
		1192: "/images/weather/white-mode/strong-or-normal-rain.png",
		1195: "/images/weather/white-mode/strong-or-normal-rain.png",
		1198: "/images/weather/white-mode/strong-or-normal-rain.png",
		1201: "/images/weather/white-mode/shower-or-drizzle.png",
		1204: "/images/weather/white-mode/patchy-cloud.png",
		1210: "/images/weather/white-mode/shower-or-drizzle.png",
		1213: "/images/weather/white-mode/snow.png",
		1216: "/images/weather/white-mode/snow.png",
		1219: "/images/weather/white-mode/snow.png",
		1222: "/images/weather/white-mode/snow.png",
		1225: "/images/weather/white-mode/snow.png",
		1237: "/images/weather/white-mode/snow.png",
		1240: "/images/weather/white-mode/shower-or-drizzle.png",
		1243: "/images/weather/white-mode/strong-or-normal-rain.png",
		1246: "/images/weather/white-mode/shower-or-drizzle.png",
		1249: "/images/weather/white-mode/strong-or-normal-rain.png",
		1252: "/images/weather/white-mode/strong-or-normal-rain.png",
		1255: "/images/weather/white-mode/snow.png",
		1258: "/images/weather/white-mode/snow.png",
		1261: "/images/weather/white-mode/snow.png",
		1264: "/images/weather/white-mode/snow.png",
		1273: "/images/weather/white-mode/thunder-with-some-rain.png",
		1276: "/images/weather/white-mode/thunder-with-some-rain.png",
		1279: "/images/weather/white-mode/thunder-with-some-rain.png",
		1282: "/images/weather/white-mode/thunder-with-some-rain.png"
	}
}
export const forecastWeatherConditions = {
	dark: {
		200: "/images/weather/dark-mode/thunder-with-some-rain.png",
		201: "/images/weather/dark-mode/thunder-with-some-rain.png",
		202: "/images/weather/dark-mode/thunder-with-some-rain.png",
		230: "/images/weather/dark-mode/rain-or-hail-or-sleek-with-thunder.png",
		231: "/images/weather/dark-mode/rain-or-hail-or-sleek-with-thunder.png",
		232: "/images/weather/dark-mode/rain-or-hail-or-sleek-with-thunder.png",
		233: "/images/weather/dark-mode/rain-or-hail-or-sleek-with-thunder.png",
		300: "/images/weather/dark-mode/shower-or-drizzle.png",
		301: "/images/weather/dark-mode/shower-or-drizzle.png",
		302: "/images/weather/dark-mode/shower-or-drizzle.png",
		500: "/images/weather/dark-mode/week-rain.png",
		501: "/images/weather/dark-mode/strong-or-normal-rain.png",
		502: "/images/weather/dark-mode/overcast-rain.png",
		511: "/images/weather/dark-mode/strong-or-normal-rain.png",
		520: "/images/weather/dark-mode/week-rain.png",
		521: "/images/weather/dark-mode/shower-or-drizzle.png",
		522: "/images/weather/dark-mode/shower-or-drizzle.png",
		600: "/images/weather/dark-mode/week-snow.png",
		601: "/images/weather/dark-mode/snow.png",
		602: "/images/weather/dark-mode/snow.png",
		610: "/images/weather/dark-mode/snow.png",
		611: "/images/weather/dark-mode/snow.png",
		612: "/images/weather/dark-mode/snow.png",
		621: "/images/weather/dark-mode/snow.png",
		622: "/images/weather/dark-mode/snow.png",
		623: "/images/weather/dark-mode/snow.png",
		700: "/images/weather/dark-mode/fog.png",
		711: "/images/weather/dark-mode/fog.png",
		721: "/images/weather/dark-mode/fog.png",
		731: "/images/weather/dark-mode/fog.png",
		741: "/images/weather/dark-mode/fog.png",
		751: "/images/weather/dark-mode/fog.png",
		800: "/images/weather/dark-mode/clear-or-hot.png",
		801: "/images/weather/dark-mode/patchy-cloud.png",
		802: "/images/weather/dark-mode/patchy-cloud.png",
		803: "/images/weather/dark-mode/overcast.png",
		804: "/images/weather/dark-mode/overcast.png",
		900: "/images/weather/dark-mode/week-rain.png"
	},
	light: {
		200: "/images/weather/white-mode/thunder-with-some-rain.png",
		201: "/images/weather/white-mode/thunder-with-some-rain.png",
		202: "/images/weather/white-mode/thunder-with-some-rain.png",
		230: "/images/weather/white-mode/rain-or-hail-or-sleek-with-thunder.png",
		231: "/images/weather/white-mode/rain-or-hail-or-sleek-with-thunder.png",
		232: "/images/weather/white-mode/rain-or-hail-or-sleek-with-thunder.png",
		233: "/images/weather/white-mode/rain-or-hail-or-sleek-with-thunder.png",
		300: "/images/weather/white-mode/shower-or-drizzle.png",
		301: "/images/weather/white-mode/shower-or-drizzle.png",
		302: "/images/weather/white-mode/shower-or-drizzle.png",
		500: "/images/weather/white-mode/week-rain.png",
		501: "/images/weather/white-mode/strong-or-normal-rain.png",
		502: "/images/weather/white-mode/overcast-rain.png",
		511: "/images/weather/white-mode/strong-or-normal-rain.png",
		520: "/images/weather/white-mode/week-rain.png",
		521: "/images/weather/white-mode/shower-or-drizzle.png",
		522: "/images/weather/white-mode/shower-or-drizzle.png",
		600: "/images/weather/white-mode/week-snow.png",
		601: "/images/weather/white-mode/snow.png",
		602: "/images/weather/white-mode/snow.png",
		610: "/images/weather/white-mode/snow.png",
		611: "/images/weather/white-mode/snow.png",
		612: "/images/weather/white-mode/snow.png",
		621: "/images/weather/white-mode/snow.png",
		622: "/images/weather/white-mode/snow.png",
		623: "/images/weather/white-mode/snow.png",
		700: "/images/weather/white-mode/fog.png",
		711: "/images/weather/white-mode/fog.png",
		721: "/images/weather/white-mode/fog.png",
		731: "/images/weather/white-mode/fog.png",
		741: "/images/weather/white-mode/fog.png",
		751: "/images/weather/white-mode/fog.png",
		800: "/images/weather/white-mode/clear-or-hot.png",
		801: "/images/weather/white-mode/patchy-cloud.png",
		802: "/images/weather/white-mode/patchy-cloud.png",
		803: "/images/weather/white-mode/overcast.png",
		804: "/images/weather/white-mode/overcast.png",
		900: "/images/weather/white-mode/week-rain.png"
	}
}
export const nightImages = {
	light: {
		1003: "/images/weather/white-mode/night/Group-6.png",
		1006: "/images/weather/white-mode/night/Group-6.png",
		1204: "/images/weather/white-mode/night/Group-5.png",
		801: "/images/weather/white-mode/night/Group-6.png",
		802: "/images/weather/white-mode/night/Group-5.png",
		800: "/images/weather/simboles/Group-1214.png",
		1000: "/images/weather/simboles/Group-1214.png"
	},
	dark: {
		1003: "/images/weather/dark-mode/night/Group-6.png",
		1006: "/images/weather/dark-mode/night/Group-6.png",
		1204: "/images/weather/dark-mode/night/Group-5.png",
		801: "/images/weather/dark-mode/night/Group-6.png",
		802: "/images/weather/dark-mode/night/Group-5.png",
		800: "/images/weather/simboles/Group-1214.png",
		1000: "/images/weather/simboles/Group-1214.png"
	}
}
export const maxAirValues = {
	PM2_5: 180,
	PM10: 300,
	CO: 5500,
	O3: 250,
	NO2: 350,
	SO2: 80
}
export const aqiRanges = [
	{threshold: 10, info: ["/images/weather/simboles/very-high.png", "Hazardous"]},
	{threshold: 9, info: ["/images/weather/simboles/high.png", "Unhealthy"]},
	{threshold: 6, info: ["/images/weather/simboles/moderate.png", "Moderate"]},
	{threshold: -Infinity, info: ["/images/weather/simboles/low.png", "Good"]}
]
export const uvColor = [
	{threshold: 2, colors: ["#70e000", "#70e0004d"]},
	{threshold: 5, colors: ["#ffea00", "#ffea004d"]},
	{threshold: 7, colors: ["#f48c06", "#f48c064d"]},
	{threshold: 10, colors: ["#E72929", "#E729294d"]},
	{threshold: Infinity, colors: ["#7b2cbf", "#7b2cbf4d"]}
]
export const biggestCities = [
	"New York",
	"Tokyo",
	"London",
	"Paris",
	"Beijing",
	"Moscow",
	"Los Angeles",
	"Shanghai",
	"Mumbai",
	"Istanbul",
	"Rio de Janeiro",
	"Sydney",
	"Dubai",
	"Singapore",
	"Mexico City",
	"Cairo",
	"Bangkok",
	"Seoul",
	"Jakarta",
	"Buenos Aires",
	"Hong Kong",
	"São Paulo",
	"Rome",
	"Madrid",
	"Toronto",
	"Lagos",
	"Berlin",
	"Chicago",
	"Kuala Lumpur",
	"Tehran",
	"Lima",
	"Dhaka",
	"Cape Town",
	"Manila",
	"Nairobi",
	"Bogotá",
	"Riyadh",
	"Baghdad",
	"Bangalore",
	"Karachi",
	"Melbourne",
	"Barcelona",
	"San Francisco",
	"Vienna",
	"Warsaw",
	"Brussels",
	"Santiago",
	"Johannesburg",
	"Casablanca",
	"Kiev",
	"Munich",
	"Athens",
	"Osaka",
	"Gaza City",
	"Hanoi",
	"Copenhagen",
	"Montreal",
	"Miami",
	"Milan",
	"Boston",
	"Stockholm",
	"Amsterdam",
	"Budapest",
	"Zurich",
	"Lisbon",
	"Prague",
	"Antwerp",
	"Dubai",
	"Venice",
	"Brisbane",
	"Edinburgh",
	"Marseille",
	"Helsinki",
	"Damascus",
	"Doha",
	"Alexandria",
	"Florence",
	"Dublin",
	"Ho Chi Minh City",
	"Rotterdam",
	"Glasgow",
	"Vancouver",
	"Tunis",
	"Addis Ababa",
	"Phnom Penh",
	"Guangzhou",
	"St. Petersburg",
	"Kathmandu",
	"Ankara",
	"Bucharest",
	"Minsk",
	"Lyon",
	"Algiers",
	"Ramallah",
	"Colombo",
	"Rabat",
	"Islamabad",
	"Abu Dhabi",
	"Amman",
	"Oslo",
	"Quito",
	"Panama City",
	"Kuala Lumpur"
]
export const continents = {
	light: {
		Africa: "/images/weather/continents/light/africa.png",
		Antarctica: "/images/weather/continents/light/antarctica.png",
		Asia: "/images/weather/continents/light/asia.png",
		Europe: "/images/weather/continents/light/europe.png",
		"North America": "/images/weather/continents/light/north-america.png",
		Oceania: "/images/weather/continents/light/oceania.png",
		"South America": "/images/weather/continents/light/south-america.png"
	},
	dark: {
		Africa: "/images/weather/continents/dark/africa.png",
		Antarctica: "/images/weather/continents/dark/antarctica.png",
		Asia: "/images/weather/continents/dark/asia.png",
		Europe: "/images/weather/continents/dark/europe.png",
		"North America": "/images/weather/continents/dark/north-america.png",
		Oceania: "/images/weather/continents/dark/oceania.png",
		"South America": "/images/weather/continents/dark/south-america.png"
	}
}
export const tempRanges = [
	{threshold: 40, color: "#d00000"},
	{threshold: 30, color: "#ff6700"},
	{threshold: 20, color: "#ffbe0b"},
	{threshold: 10, color: "#70e000"},
	{threshold: 0, color: "#80ed99"},
	{threshold: -10, color: "#48bfe3"},
	{threshold: -20, color: "#5e60ce"},
	{threshold: -Infinity, color: "#7400b8"}
]
