export const weatherConditions = {
	dark: {
		1000: "/images/weather/dark mode/clear or hot.png",
		1003: "/images/weather/dark mode/patchy cloud.png",
		1006: "/images/weather/dark mode/patchy cloud.png",
		1009: "/images/weather/dark mode/overcast.png",
		1030: "/images/weather/dark mode/fog.png",
		1063: "/images/weather/dark mode/week rain.png",
		1066: "/images/weather/dark mode/week snow.png",
		1069: "/images/weather/dark mode/shower or drizzle.png",
		1072: "/images/weather/dark mode/shower or drizzle.png",
		1087: "/images/weather/dark mode/shower or drizzle.png",
		1114: "/images/weather/dark mode/snow.png",
		1117: "/images/weather/dark mode/snow.png",
		1135: "/images/weather/dark mode/fog.png",
		1147: "/images/weather/dark mode/fog.png",
		1150: "/images/weather/dark mode/wind.png",
		1153: "/images/weather/dark mode/wind.png",
		1168: "/images/weather/dark mode/shower or drizzle.png",
		1171: "/images/weather/dark mode/shower or drizzle.png",
		1180: "/images/weather/dark mode/hot.png",
		1183: "/images/weather/dark mode/week rain.png",
		1186: "/images/weather/dark mode/hot.png",
		1189: "/images/weather/dark mode/strong or normal rain.png",
		1192: "/images/weather/dark mode/strong or normal rain.png",
		1195: "/images/weather/dark mode/strong or normal rain.png",
		1198: "/images/weather/dark mode/strong or normal rain.png",
		1201: "/images/weather/dark mode/shower or drizzle.png",
		1204: "/images/weather/dark mode/patchy cloud.png",
		1210: "/images/weather/dark mode/shower or drizzle.png",
		1213: "/images/weather/dark mode/snow.png",
		1216: "/images/weather/dark mode/snow.png",
		1219: "/images/weather/dark mode/snow.png",
		1222: "/images/weather/dark mode/snow.png",
		1225: "/images/weather/dark mode/snow.png",
		1237: "/images/weather/dark mode/snow.png",
		1240: "/images/weather/dark mode/thunder with some rain.png",
		1243: "/images/weather/dark mode/strong or normal rain.png",
		1246: "/images/weather/dark mode/shower or drizzle.png",
		1249: "/images/weather/dark mode/strong or normal rain.png",
		1252: "/images/weather/dark mode/strong or normal rain.png",
		1255: "/images/weather/dark mode/snow.png",
		1258: "/images/weather/dark mode/snow.png",
		1261: "/images/weather/dark mode/snow.png",
		1264: "/images/weather/dark mode/snow.png",
		1273: "/images/weather/dark mode/thunder with some rain.png",
		1276: "/images/weather/dark mode/thunder with some rain.png",
		1279: "/images/weather/dark mode/thunder with some rain.png",
		1282: "/images/weather/dark mode/thunder with some rain.png",
	},
	light: {
		1000: "/images/weather/white mode/clear or hot.png",
		1003: "/images/weather/white mode/patchy cloud.png",
		1006: "/images/weather/white mode/patchy cloud.png",
		1009: "/images/weather/white mode/overcast.png",
		1030: "/images/weather/white mode/fog.png",
		1063: "/images/weather/white mode/week rain.png",
		1066: "/images/weather/white mode/week snow.png",
		1069: "/images/weather/white mode/shower or drizzle.png",
		1072: "/images/weather/white mode/shower or drizzle.png",
		1087: "/images/weather/white mode/shower or drizzle.png",
		1114: "/images/weather/white mode/snow.png",
		1117: "/images/weather/white mode/snow.png",
		1135: "/images/weather/white mode/fog.png",
		1147: "/images/weather/white mode/fog.png",
		1150: "/images/weather/white mode/wind.png",
		1153: "/images/weather/white mode/wind.png",
		1168: "/images/weather/white mode/shower or drizzle.png",
		1171: "/images/weather/white mode/shower or drizzle.png",
		1180: "/images/weather/white mode/hot.png",
		1183: "/images/weather/white mode/week rain.png",
		1186: "/images/weather/white mode/hot.png",
		1189: "/images/weather/white mode/strong or normal rain.png",
		1192: "/images/weather/white mode/strong or normal rain.png",
		1195: "/images/weather/white mode/strong or normal rain.png",
		1198: "/images/weather/white mode/strong or normal rain.png",
		1201: "/images/weather/white mode/shower or drizzle.png",
		1204: "/images/weather/white mode/patchy cloud.png",
		1210: "/images/weather/white mode/shower or drizzle.png",
		1213: "/images/weather/white mode/snow.png",
		1216: "/images/weather/white mode/snow.png",
		1219: "/images/weather/white mode/snow.png",
		1222: "/images/weather/white mode/snow.png",
		1225: "/images/weather/white mode/snow.png",
		1237: "/images/weather/white mode/snow.png",
		1240: "/images/weather/white mode/thunder with some rain.png",
		1243: "/images/weather/white mode/strong or normal rain.png",
		1246: "/images/weather/white mode/shower or drizzle.png",
		1249: "/images/weather/white mode/strong or normal rain.png",
		1252: "/images/weather/white mode/strong or normal rain.png",
		1255: "/images/weather/white mode/snow.png",
		1258: "/images/weather/white mode/snow.png",
		1261: "/images/weather/white mode/snow.png",
		1264: "/images/weather/white mode/snow.png",
		1273: "/images/weather/white mode/thunder with some rain.png",
		1276: "/images/weather/white mode/thunder with some rain.png",
		1279: "/images/weather/white mode/thunder with some rain.png",
		1282: "/images/weather/white mode/thunder with some rain.png",
	},
}
export const maxAirValues = {
	PM2_5: 180,
	PM10: 300,
	CO: 5500,
	O3: 250,
	NO2: 350,
	SO2: 80,
}
export const aqiImage = {
	1: ["/images/weather/simboles/low.png", "Good"],
	2: ["/images/weather/simboles/low.png", "Good"],
	3: ["/images/weather/simboles/low.png", "Good"],
	4: ["/images/weather/simboles/moderate.png", "Moderate"],
	5: ["/images/weather/simboles/moderate.png", "Moderate"],
	6: ["/images/weather/simboles/moderate.png", "Moderate"],
	7: ["/images/weather/simboles/high.png", "Unhealthy"],
	8: ["/images/weather/simboles/high.png", "Unhealthy"],
	9: ["/images/weather/simboles/high.png", "Unhealthy"],
	10: ["/images/weather/simboles/very high.png", "Hazardous"],
}
