export const weatherConditions = {
  dark: {
    1000: "/images/weather/dark mode/clear or hot.png",
    1003: "/images/weather/dark mode/patchy cloud.png",
    1006: "/images/weather/dark mode/patchy cloud.png",
    1009: "/images/weather/dark mode/overcast.png",
    1030: "/images/weather/dark mode/fog.png",
    1135: "/images/weather/dark mode/fog.png",
    1063: "/images/weather/dark mode/week rain.png",
    1066: "/images/weather/dark mode/week snow.png",
    1069: "/images/weather/dark mode/hail or sleek.png",
    1072: "/images/weather/dark mode/patchy freezing drizzle.png",
    1073: "/images/weather/dark mode/strong or normal rain.png",
    1076: "/images/weather/dark mode/strong or normal rain.png",
    1087: "/images/weather/dark mode/shower or drizzle.png",
    1083: "/images/weather/dark mode/shower or drizzle.png",
    1084: "/images/weather/dark mode/shower or drizzle.png",
    1114: "/images/weather/dark mode/snow.png",
    1117: "/images/weather/dark mode/snow.png",
    1121: "/images/weather/dark mode/snow.png",
    1147: "/images/weather/dark mode/fog.png",
    1150: "/images/weather/dark mode/wind.png",
    1153: "/images/weather/dark mode/wind.png",
    1168: "/images/weather/dark mode/wind.png",
    1171: "/images/weather/dark mode/wind with cloud.png",
    1180: "/images/weather/symbols/hot.png",
    1183: "/images/weather/symbols/Union.png",
    1186: "/images/weather/symbols/hot.png",
    1062: "/images/weather/dark mode/rain.png",
    1078: "/images/weather/dark mode/shower or drizzle.png",
    1120: "/images/weather/dark mode/heavy rain.png",
    1119: "/images/weather/dark mode/heavy snow.png",
    1132: "/images/weather/dark mode/snow.png",
    1189: "/images/weather/dark mode/strong or normal rain.png",
    1195: "/images/weather/dark mode/strong or normal rain.png",
    1198: "/images/weather/dark mode/strong or normal rain.png",
    1204: "/images/weather/dark mode/patchy cloud.png",
    1207: "/images/weather/dark mode/week snow.png",
    1210: "/images/weather/dark mode/shower or drizzle.png",
    1213: "/images/weather/dark mode/snow.png",
    1216: "/images/weather/dark mode/snow.png",
    1225: "/images/weather/dark mode/snow.png",
    1258: "/images/weather/dark mode/snow.png",
  },
  light: {
    1000: "/images/weather/white mode/clear or hot.png",
    1003: "/images/weather/white mode/patchy cloud.png",
    1006: "/images/weather/white mode/patchy cloud.png",
    1009: "/images/weather/white mode/overcast.png",
    1030: "/images/weather/white mode/fog.png",
    1135: "/images/weather/white mode/fog.png",
    1063: "/images/weather/white mode/week rain.png",
    1066: "/images/weather/white mode/week snow.png",
    1069: "/images/weather/white mode/hail or sleek.png",
    1072: "/images/weather/white mode/patchy freezing drizzle.png",
    1073: "/images/weather/white mode/strong or normal rain.png",
    1076: "/images/weather/white mode/strong or normal rain.png",
    1087: "/images/weather/white mode/shower or drizzle.png",
    1083: "/images/weather/white mode/shower or drizzle.png",
    1084: "/images/weather/white mode/shower or drizzle.png",
    1114: "/images/weather/white mode/snow.png",
    1117: "/images/weather/white mode/snow.png",
    1121: "/images/weather/white mode/snow.png",
    1147: "/images/weather/white mode/fog.png",
    1150: "/images/weather/white mode/wind.png",
    1153: "/images/weather/white mode/wind.png",
    1168: "/images/weather/white mode/wind.png",
    1171: "/images/weather/white mode/wind with cloud.png",
    1180: "/images/weather/symbols/hot.png",
    1183: "/images/weather/symbols/Union.png",
    1186: "/images/weather/symbols/hot.png",
    1062: "/images/weather/white mode/rain.png",
    1078: "/images/weather/white mode/shower or drizzle.png",
    1120: "/images/weather/white mode/strong or normal rain.png",
    1119: "/images/weather/white mode/snow.png",
    1132: "/images/weather/white mode/ice pellets.png",
    1189: "/images/weather/white mode/strong or normal rain.png",
    1195: "/images/weather/white mode/strong or normal rain.png",
    1198: "/images/weather/white mode/strong or normal rain.png",
    1204: "/images/weather/white mode/patchy cloud.png",
    1207: "/images/weather/white mode/week snow.png",
    1210: "/images/weather/white mode/shower or drizzle.png",
    1213: "/images/weather/white mode/snow.png", 
    1216: "/images/weather/white mode/snow.png",
    1225: "/images/weather/white mode/snow.png",
    1258: "/images/weather/white mode/snow.png",
  },
}
